basePath: /
definitions:
  model.Site:
    properties:
      createdAt:
        description: User       User
        type: string
      id:
        type: integer
      locationId:
        type: string
      updatedAt:
        type: string
      userID:
        type: integer
    type: object
  model.User:
    properties:
      createdAt:
        type: string
      email:
        type: string
      password:
        type: string
      sites:
        items:
          $ref: '#/definitions/model.Site'
        type: array
      token:
        type: string
      updatedAt:
        type: string
    type: object
  model.UserSignup:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server for the Frontend TEST API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Circutor Frontend TEST API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Login a user
      parameters:
      - description: user signup
        in: body
        name: user
        schema:
          $ref: '#/definitions/model.UserSignup'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      summary: Login
  /signup:
    get:
      consumes:
      - application/json
      description: Signs up a user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      summary: Signup
swagger: "2.0"
